### ISSUE TITLE
3.0.11 release

### ISSUE THREAD

**Issue by soosdonat** [deviddev/billingo-api-v3-php-sdk#2]
Sziasztok! 

Szeretnék érdeklődni, hogy az SDK mikor lesz kompatibilis az API 3.0.11-el? Legfőképp a partner névben való szűrés miatt érdekelne.

Köszönöm előre is!
Donát

**Comment by deviddev** [comment]
Szia!

Sajnos eléggé időhiányban vagyok, de a héten megpróbálom megnézni és letesztelni a 3.0.11-et, mert ez csak azért került fel, hogy a [Billingo API V3 PHP and Laravel Wrapper](https://github.com/deviddev/billingo-api-v3-php-and-laravel-wrapper) -nek meglegyen a függősége.

**Comment by soosdonat** [comment]
Rendben, nagyon köszönöm a választ!

**Comment by deviddev** [comment]
Szia @soosdonat !

Most volt időm csak vele foglalkozni, a [0.2.1-es release](https://github.com/deviddev/billingo-api-v3-php-sdk/releases/tag/0.2.1) már 3.0.11-el van feltéve, ha még aktuális.

**Comment by soosdonat** [comment]
Szia @deviddev !

Szuper, nagyon köszönjük!

**Comment by soosdonat** [comment]
Szia @deviddev !

Kipróbáltuk, tökéletesen működik a név szerinti keresés, viszont olyan hibába ütköztünk, miszerint ha több partnerünk is van ugyanazzal a névvel, akkor az automatizmussal nem fogjuk tudni eldönteni, hogy melyikkel is kell a továbbiakban dolgoznunk. Van erre esetleg valamilyen kész megoldás? Vagy lehetne kiegészíteni a szűrést e-mail címre is?

**Comment by deviddev** [comment]
Szia @soosdonat !

Én csak egy forkot tettem fel a [hivatalos api](https://app.swaggerhub.com/apis/Billingo/Billingo)-ból, hogy egyszerűbb legyen elérni (pontosabban, hogy egyáltalán el lehessen érni) composerrel, valamint, mint már fentebb említettem a [PHP és Laravel wrappernek](https://github.com/deviddev/billingo-api-v3-php-and-laravel-wrapper) kellet függőségként.

Ha gondoljátok az egy jól bővíthető "fluent" wrappert húz e felé a swaggeres, automatikusan generált csúnyaság felé.

Mivel nincs közöm a Billingo-hoz, így sajnos nem tudom megmondani, hogy ők mikor és mit fognak fejleszteni, ha jön ki új csomag, az idővel fel fog ide is kerülni, de ugye ez nem "hivatalos" oldal csak egy "fork" féleség.

Ezután szerintem a Billingo for Developers facebook csoportban érdeklődj, elég gyorsan szoktak reagálni és ha esetleg ilyen nincs tervben nekik lehet emiatt fogják megcsinálni, így mindenképp érdemes,.

A billingos api-t átfutva én jelenleg nem látok rá kész megoldást.

**Comment by soosdonat** [comment]
Szia @deviddev !

Ja értem, tiszta sor! Nagyon köszönöm a választ!
