### ISSUE TITLE
PHP verzió támogatás

### ISSUE THREAD

**Issue by ghost** [deviddev/billingo-api-v3-php-sdk#3]
Sziasztok!

Belefutottunk egy olyanba, hogy 

```
x@aspire:/tmp/SwaggerClient-php$ composer install
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - friendsofphp/php-cs-fixer[v1.12.0, ..., v1.13.3] require php ^5.3.6 || >=7.0 <7.2 -> your php version (7.4.3) does not satisfy that requirement.
    - Root composer.json requires friendsofphp/php-cs-fixer ~1.12 -> satisfiable by friendsofphp/php-cs-fixer[v1.12.0, ..., v1.13.3].
```

Egyelőre lerántottuk 7.2-re és copy-paste-eljük a függőségekkel együtt, de nem szívesen csináljuk ezt a gányolást. Tudnátok valamit kezdeni ezzel, hogy rendesen lehessen 7.4.x-re is telepíteni composerrel?

**Comment by deviddev** [comment]
Szia!

Ez csak dev függőség, vagy ne tegyétek fel a dev dependency-ket vagy most frissítésre került a csomag, kikreült a régi php unit és az SDK is frissült a v3.0.13-ra, úgyhogy frissítsétek le a v0.2.4-ra.

Üdv.

**Comment by ghost** [comment]
@deviddev Szia! Próbáltuk dev dependency nélkül is, de úgy is ezt írta. Nem értem én sem, hogy miért.

**Comment by ghost** [comment]
Megnézem akkor az újabb verziókkal, kíváncsi vagyok.
